# HW1_ex_2_1_3

In [4]:
import numpy as np

#defining random weights and bias

# Weights
W = np.array([[1,0],[1,1],[1/3,1]])

# biases
b = np.array([[-1],[-6],[-2]])

# input
p = np.array([[2],[0]])

# output of summation
n = np.matmul(W,p)+b

# output of activation function
a = np.heaviside(n,1)

# Results
print(n.T)
print(a)

[[ 1.         -4.         -1.33333333]]
[[1.]
 [0.]
 [0.]]


# HW1_ex_2_2

In [1]:
import numpy as np

def BinaryCrossEntropy(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-7, 1 - 1e-7)
    term_0 = (1-y_true) * np.log(1-y_pred + 1e-7)
    print(term_0,"aaaaaaaaaaaaaaaaaaaaaaa")
    term_1 = y_true * np.log(y_pred + 1e-7)
    return -np.mean(term_0+term_1, axis=0)

def sigmoid(x):

    return  1/(1+np.exp(-x))

# input
p = np.array([[[0], [-1],[2], [-1]],
              [[0], [1], [0], [-1]],
              [[0], [2], [-1], [1]]])
label = np.array([0, 0, 1, 1])


# defining weights and biases for first layer

mu, sigma = 0, 1 # mean and standard deviation

W1 = np.random.normal(mu, sigma, (3,3))
b1 = np.random.normal(mu, sigma, (3,1))
W2 = np.random.normal(mu, sigma, (1,3))
b2 = np.random.normal(mu, sigma, (1,1))

# outputs for ReLU activation funtion
output_batch = np.zeros((1,4))
for i in range(p.shape[1]):
    n1 = np.matmul(W1,p[:,i,:])+b1
    a1 = np.maximum(0,n1)
    n2 = np.matmul(W2,a1)+b2
    output_batch[0,i] = sigmoid(n2)

loss = BinaryCrossEntropy(label.reshape(-1, 1), output_batch[0,:].reshape(-1,1))
print(f"outputs for ReLU activation funtion:{output_batch} and Loss={loss}\n")

# outputs for tanh activation funtion
for i in range(p.shape[1]):
    n1 = np.matmul(W1,p[:,i,:])+b1
    a1 = np.tanh(n1)
    n2 = np.matmul(W2,a1)+b2
    output_batch[0,i] = sigmoid(n2)

loss = BinaryCrossEntropy(label.reshape(-1, 1), output_batch[0,:].reshape(-1,1))
print(f"outputs for tanh activation funtion:{output_batch} and Loss={loss}\n")

# outputs for Sigmoid activation funtion
for i in range(p.shape[1]):
    n1 = np.matmul(W1,p[:,i,:])+b1
    a1 = sigmoid(n1)
    n2 = np.matmul(W2,a1)+b2
    output_batch[0,i] = sigmoid(n2)

loss = BinaryCrossEntropy(label.reshape(-1, 1), output_batch[0,:].reshape(-1,1))
print(f"outputs for Sigmoid activation funtion:{output_batch} and Loss={loss}\n")

# outputs for Linear activation funtion
for i in range(p.shape[1]):
    n1 = np.matmul(W1,p[:,i,:])+b1
    a1 = n1
    n2 = np.matmul(W2,a1)+b2
    output_batch[0,i] = sigmoid(n2)

loss = BinaryCrossEntropy(label.reshape(-1, 1), output_batch[0,:].reshape(-1,1))
print(f"outputs for Linear activation funtion:{output_batch} and Loss={loss}\n")


[[-0.34934275]
 [-0.02889362]
 [-0.        ]
 [-0.        ]] aaaaaaaaaaaaaaaaaaaaaaa
outputs for ReLU activation funtion:[[0.2948487  0.02848029 0.33748788 0.13806312]] and Loss=[0.86112633]

[[-0.82138148]
 [-0.64480359]
 [-0.        ]
 [-0.        ]] aaaaaaaaaaaaaaaaaaaaaaa
outputs for tanh activation funtion:[[0.56017647 0.4752345  0.59178083 0.50861935]] and Loss=[0.66671475]

[[-0.22606746]
 [-0.19227383]
 [-0.        ]
 [-0.        ]] aaaaaaaaaaaaaaaaaaaaaaa
outputs for Sigmoid activation funtion:[[0.20233581 0.17491919 0.20479032 0.20281323]] and Loss=[0.89989468]

[[-1.08965744]
 [-0.24766392]
 [-0.        ]
 [-0.        ]] aaaaaaaaaaaaaaaaaaaaaaa
outputs for Linear activation funtion:[[0.66366841 0.21937785 0.66838643 0.74763651]] and Loss=[0.50776205]



C:\Users\TUF\AppData\Local\Temp\ipykernel_15632\3149061997.py:36: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  output_batch[0,i] = sigmoid(n2)
C:\Users\TUF\AppData\Local\Temp\ipykernel_15632\3149061997.py:46: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  output_batch[0,i] = sigmoid(n2)
C:\Users\TUF\AppData\Local\Temp\ipykernel_15632\3149061997.py:56: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  output_batch[0,i] = sigmoid(n2)
C:\Users\TUF\AppData\Local\Temp\ipyke

In [34]:
np.array([1, 1, 1]).reshape(-1, 1)

array([[1],
       [1],
       [1]])

# HW1_ex_2_3

In [24]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def cross_E(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred + 10**-100))


# input
p = np.array([[[-1], [-1],[0], [1],[2],[2]],
              [[1], [0], [2], [2],[0],[1]]])

label = np.array([[[1], [1], [0], [0],[0],[0]],
                  [[0], [0], [1], [1],[0],[0]],
                  [[0], [0], [0], [0],[1],[1]]])


# defining weights and biases for first layer

W1 = np.random.uniform(-4, 4, (4,2))
b1 = np.random.uniform(-4, 4, (4,1))
W2 = np.random.uniform(-4, 4, (3,4))
b2 = np.random.uniform(-4, 4, (3,1))

# forward prop
output_batch = np.zeros((3,6,1))
for i in range(p.shape[1]):
    n1 = np.matmul(W1,p[:,i,:])+b1
    a1 = np.maximum(0,n1)
    n2 = np.matmul(W2,a1)+b2
    output_batch[:,i,:] = softmax(n2)

# calculating loss and accuracy for each input

loss=[]
for i in range(output_batch.shape[1]):

    loss.append(cross_E(label[:,i,:],output_batch[:,i,:]))

correct=0
for j in loss:

    if j<=0.6931:
        correct+=1

accuracy=correct/6

print(f"loss={loss}\n")
print(f"accuracy={accuracy}")





loss=[0.0020542170348809424, 0.23363887901578734, 23.2248220016289, 39.440613393529915, 11.769378668155811, 25.750243022680564]

accuracy=0.3333333333333333


In [14]:
a = np.array([[[1], [1], [0], [0],[0],[0]],
              [[0], [0], [1], [1],[0],[0]],
              [[0], [0], [0], [0],[1],[1]]])

b= np.array([[[0.5], [0.5], [0], [0],[0],[0]],
             [[0], [0], [0.5], [0.5],[0],[0]],
             [[0], [0], [0], [0],[0.5],[0.5]]])

loss1=[]
for i in range(output_batch.shape[1]):

    loss1.append(cross_E(a[:,i,:],b[:,i,:]))

loss1

[0.6931471805599453,
 0.6931471805599453,
 0.6931471805599453,
 0.6931471805599453,
 0.6931471805599453,
 0.6931471805599453]